####
# This Containerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Before building the container image run:
#
# mvn package
#
# Then, build the image with:
#
# podman build -t <your_tag> .
#
# Then run the container using:
#
# podman run -i --rm -p 8080:8080 <your_tag>
#
###
FROM registry.ocp4.example.com:8443/ubi8/ubi:8.6
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV AB_ENABLED=jmx_exporter

# Be prepared for running in OpenShift too
RUN mkdir /deployments \
  && adduser -G root --no-create-home -u 1001 quarkus \
  && chown -R 1001 /deployments \
  && chmod -R "g+rwX" /deployments \
  && chown -R 1001:root /deployments

RUN yum -y install java-17-openjdk-devel

COPY --chown=1001:root target/*-runner.jar /deployments/app.jar
EXPOSE 8080 8778 9779

# run with user 1001
USER 1001

CMD ["java","-jar","/deployments/app.jar"]