apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: USER_NAME_PLACEHOLDER-istio-system
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: USER_NAME_PLACEHOLDER-istio-system
spec:
  config:
    exporters:
      otlp/north:
        auth:
          authenticator: bearertokenauth
        endpoint: tempo-sample-gateway.tracing-system.svc.cluster.local:8090
        headers:
          X-Scope-OrgID: north
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          insecure: false
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
      - bearertokenauth
      pipelines:
        traces:
          exporters:
          - otlp/north
          receivers:
          - otlp
  mode: deployment
  replicas: 1
  serviceAccount: otel-collector
