apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmonitor-editor-aggregate
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - servicemonitors
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-all-to-manage-podmonitors
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podmonitor-editor-aggregate
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-labeler
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-homeroom-to-label-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-labeler
subjects:
- kind: Group
  name: system:serviceaccounts:homeroom
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali-istio-extended-permissions
rules:
- apiGroups:
  - networking.istio.io
  - security.istio.io
  - telemetry.istio.io
  - kiali.io
  resources:
  - '*'
  verbs:
  - '*'
