apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmonitor-editor-aggregate
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - servicemonitors
  verbs:
  - '*'
